export const INITIAL_CATEGORIES = [
	{
		id: "cat-fitness",
		name: "Fitness",
		categoryColor: "#FF5722",
		description: "Physical health and training",
	},
	{
		id: "cat-home-cleaning",
		name: "Home Cleaning",
		categoryColor: "#2196F3",
		description: "Maintenance and cleaning tasks",
	},
	{
		id: "cat-home-organization",
		name: "Home Organization",
		categoryColor: "#9C27B0",
		description: "Decluttering and organizing spaces",
	},
	{
		id: "cat-resources",
		name: "Resources Management",
		categoryColor: "#4CAF50",
		description: "Inventory and supplies",
	},
	{
		id: "cat-health",
		name: "Health Activities",
		categoryColor: "#E91E63",
		description: "Wellbeing and medical",
	},
	{
		id: "cat-meals",
		name: "Meals",
		categoryColor: "#FFC107",
		description: "Cooking and eating",
	},
	{
		id: "cat-hobbies",
		name: "Hobbies",
		categoryColor: "#00BCD4",
		description: "Leisure and interest",
	},
	{
		id: "cat-studies",
		name: "Studies",
		categoryColor: "#3F51B5",
		description: "Education and learning",
	},
	{
		id: "cat-professional",
		name: "Professional",
		categoryColor: "#607D8B",
		description: "Work and career",
	},
	{
		id: "cat-social",
		name: "Social & Family",
		categoryColor: "#009688",
		description: "Presence and contribution to others",
	},
	{
		id: "cat-philosophy",
		name: "Philosophy & Mindset",
		categoryColor: "#673AB7",
		description: "Existential purpose and mental frameworks",
	},
	{
		id: "cat-strategic",
		name: "Strategy & Wealth",
		categoryColor: "#FF9800",
		description: "Long-term planning and independence",
	},
];

export const INITIAL_TAGS = [
	{ id: "tag-urgent", name: "Urgent Priority", colorHex: "#D32F2F" },
	{ id: "tag-critical", name: "Critical Priority", colorHex: "#B71C1C" },
	{ id: "tag-low-priority", name: "Low Priority", colorHex: "#8BC34A" },
	{ id: "tag-low-energy", name: "Low Energy", colorHex: "#FFEB3B" },
	{ id: "tag-balanced-energy", name: "Balanced Energy", colorHex: "#FF9800" },
	{ id: "tag-high-energy", name: "High Energy", colorHex: "#F44336" },
	{ id: "tag-preparation", name: "Preparation", colorHex: "#9E9E9E" },
];

export const INITIAL_FREQUENCIES = [
	{
		id: "freq-daily",
		type: "repeat",
		name: "Daily",
		frequencyPeriod: "day",
		amount: 1,
		repeat: true,
	},
	{
		id: "freq-workdays",
		type: "repeat",
		name: "Work Days",
		frequencyPeriod: "day",
		amount: 1,
		repeat: true,
	},
	{
		id: "freq-weekend",
		type: "repeat",
		name: "Weekend",
		frequencyPeriod: "day",
		amount: 1,
		repeat: true,
	},
	{
		id: "freq-oneshot",
		type: "once",
		name: "One shot",
		frequencyPeriod: "once",
		amount: 1,
		repeat: false,
	},
	{
		id: "freq-hourly",
		type: "repeat",
		name: "Hourly",
		frequencyPeriod: "hour",
		amount: 1,
		repeat: true,
	},
	{
		id: "freq-weekly",
		type: "repeat",
		name: "Weekly",
		frequencyPeriod: "week",
		amount: 1,
		repeat: true,
	},
];

export const INITIAL_MEANINGS = [
	{
		id: "mean-self-sufficient",
		categoryId: "cat-health",
		name: "Self-Sufficient",
		description: "Physical and personal independence (Independência física).",
		isSynced: true,
	},
	{
		id: "mean-financial-freedom",
		categoryId: "cat-strategic",
		name: "Financial Freedom",
		description:
			"Financial independence and strategic security (Independência financeira).",
		isSynced: true,
	},
	{
		id: "mean-helping-others",
		categoryId: "cat-social",
		name: "Helping Others",
		description: "Empowering and facilitating life for those around me.",
		isSynced: true,
	},
	{
		id: "mean-human-experience",
		categoryId: "cat-studies",
		name: "Deep Connections",
		description: "Learning from personal stories and human experiences.",
		isSynced: true,
	},
	{
		id: "mean-mental-vitality",
		categoryId: "cat-health",
		name: "Mental Vitality",
		description:
			"Maintaining life-affirming habits and physiological wellbeing.",
		isSynced: true,
	},
	{
		id: "mean-presence",
		categoryId: "cat-social",
		name: "Presence",
		description: "Being truly available for the people I love.",
		isSynced: true,
	},
	{
		id: "mean-art-vitality",
		categoryId: "cat-hobbies",
		name: "Vital Artistry",
		description: "Art as a fundamental driver of existence.",
		isSynced: true,
	},
	{
		id: "mean-manifestation",
		categoryId: "cat-hobbies",
		name: "Dream Manifestation",
		description: "Creative acts that give form to internal dreams and visions.",
		isSynced: true,
	},
	{
		id: "mean-active-absurdism",
		categoryId: "cat-philosophy",
		name: "Active Absurdism",
		description:
			"Life has no inherent meaning; I am the creator of my own purpose.",
		isSynced: true,
	},
	{
		id: "mean-temporal-presence",
		categoryId: "cat-philosophy",
		name: "Temporal Presence",
		description:
			"The present moment defines the scope and meaning of past and future.",
		isSynced: true,
	},
];

export const INITIAL_HABITS = [
	{
		id: "habit-daily-walk",
		name: "Daily 1-Hour Walk",
		description:
			"Consistent cardiovascular activity for mental and physical health.",
		categoryId: "cat-fitness",
		frequencyId: "freq-daily",
		isSynced: true,
	},
	{
		id: "habit-smoke-free",
		name: "Smoke-Free Life",
		description:
			"Daily commitment to respiratory health and freedom from nicotine.",
		categoryId: "cat-health",
		frequencyId: "freq-daily",
		isSynced: true,
	},
	{
		id: "habit-daily-meditation",
		name: "Daily Meditation",
		description: "Cultivating focus and existential presence.",
		categoryId: "cat-philosophy",
		frequencyId: "freq-daily",
		isSynced: true,
	},
	{
		id: "habit-hydration",
		name: "2L Daily Hydration",
		description:
			"Maintaining optimal hydration levels for cognitive performance.",
		categoryId: "cat-health",
		frequencyId: "freq-daily",
		isSynced: true,
	},
	{
		id: "habit-weekly-workout",
		name: "Weekly Workout",
		description: "Resistance training and strength maintenance.",
		categoryId: "cat-fitness",
		frequencyId: "freq-weekly",
		isSynced: true,
	},
	{
		id: "habit-weekly-pilates",
		name: "Weekly Pilates",
		description: "Core strength, flexibility, and controlled movement.",
		categoryId: "cat-fitness",
		frequencyId: "freq-weekly",
		isSynced: true,
	},
];

export const INITIAL_GOALS = [
	{
		id: "goal-5k-run",
		categoryId: "cat-fitness",
		meaningId: "mean-self-sufficient",
		name: "Run a 5K",
		description:
			"Build cardiovascular capacity to complete a 5K race without stopping.",
		status: "active",
		isSynced: true,
	},
	{
		id: "goal-read-12",
		categoryId: "cat-studies",
		meaningId: "mean-human-experience",
		name: "12 Books in 1 Year",
		description: "Expand worldview by reading one impactful book per month.",
		status: "active",
		isSynced: true,
	},
	{
		id: "goal-daily-health",
		categoryId: "cat-health",
		meaningId: "mean-mental-vitality",
		name: "Daily Physical Self-Care",
		description: "Treating the body as a temple for the strategic mind.",
		status: "active",
		isSynced: true,
	},
	{
		id: "goal-home-server",
		categoryId: "cat-professional",
		meaningId: "mean-financial-freedom",
		name: "Local Home Server",
		description: "Deploying a local strategic infrastructure for data privacy.",
		status: "active",
		isSynced: true,
	},
	{
		id: "goal-ai-mastery",
		categoryId: "cat-philosophy",
		meaningId: "mean-human-experience",
		name: "AI Fundamentals",
		description: "Understanding the foundations of machine intelligence.",
		status: "active",
		isSynced: true,
	},
	{
		id: "goal-personal-hub",
		categoryId: "cat-professional",
		meaningId: "mean-manifestation",
		name: "Personal Organization Hub",
		description: "Building the digital engine to drive life strategy.",
		status: "active",
		isSynced: true,
	},
	{
		id: "goal-weekly-art",
		categoryId: "cat-hobbies",
		meaningId: "mean-art-vitality",
		name: "Year-Round Artistic Expression",
		description: "Creating art in at least 40 weeks per year.",
		status: "active",
		isSynced: true,
	},
	{
		id: "goal-mental-care",
		categoryId: "cat-health",
		meaningId: "mean-mental-vitality",
		name: "Daily Mental Resilience",
		description: "Consistent mental maintenance to ensure peak performance.",
		status: "active",
		isSynced: true,
	},
	{
		id: "goal-sleep-hygiene",
		categoryId: "cat-health",
		meaningId: "mean-mental-vitality",
		name: "Consistent Sleep Hygiene",
		description: "Regulating Circadian rhythms for cognitive longevity.",
		status: "active",
		isSynced: true,
	},
];

export const INITIAL_TASKS = [
	{
		id: "task-buy-shoes",
		goalId: "goal-5k-run",
		title: "Buy Running Shoes",
		description: "Acquiring professional gear to avoid injury.",
		status: "todo",
		priority: "high",
		isSynced: true,
	},
	{
		id: "task-visit-store",
		parentTaskId: "task-buy-shoes",
		goalId: "goal-5k-run",
		title: "Visit Physical Store",
		description: "Test multiple models for ergonomic support.",
		status: "todo",
		isSynced: true,
	},
	{
		id: "task-buy-pi",
		goalId: "goal-home-server",
		title: "Buy Raspberry Pi",
		description: "Purchase the compute core for the home server project.",
		status: "todo",
		priority: "medium",
		isSynced: true,
	},
	{
		id: "task-monthly-investment",
		goalId: "goal-home-server",
		title: "Monthly Investment Strategy",
		description: "Strategic capital allocation for financial freedom.",
		status: "todo",
		priority: "high",
		isSynced: true,
	},
	{
		id: "task-strat-reserve",
		parentTaskId: "task-monthly-investment",
		goalId: "goal-home-server",
		title: "Invest in Monthly Reserve",
		description: "Allocating funds for standard strategic growth.",
		status: "todo",
		isSynced: true,
	},
	{
		id: "task-emergency-reserve",
		parentTaskId: "task-monthly-investment",
		goalId: "goal-home-server",
		title: "Emergency Fund Deposit",
		description: "Strengthening the resilience buffer.",
		status: "todo",
		isSynced: true,
	},
	{
		id: "task-study-llm",
		goalId: "goal-ai-mastery",
		title: "Study LLM Architectures",
		description: "Deep dive into Transformers and attention mechanisms.",
		status: "todo",
		isSynced: true,
	},
	{
		id: "task-study-agents",
		goalId: "goal-ai-mastery",
		title: "Agentic AI Frameworks",
		description: "Review Langchain, AutoGen, and custom agent logic.",
		status: "todo",
		isSynced: true,
	},
	{
		id: "task-study-go",
		goalId: "goal-ai-mastery",
		title: "Go Language Foundation",
		description: "Mastering concurrency and high-performance backend patterns.",
		status: "todo",
		isSynced: true,
	},
	{
		id: "task-study-ds",
		goalId: "goal-personal-hub",
		title: "Design Systems Masterclass",
		description: "Establishing the UI/UX pattern language for LiveRubber.",
		status: "todo",
		isSynced: true,
	},
	{
		id: "task-pilates",
		goalId: "goal-daily-health",
		title: "Pilates Session",
		description: "Execute core strength and flexibility routine.",
		status: "todo",
		isSynced: true,
	},
	{
		id: "task-walk-1h",
		goalId: "goal-5k-run",
		title: "1-Hour Endurance Walk",
		description: "Developing basic cardiovascular base.",
		status: "todo",
		isSynced: true,
	},
	{
		id: "task-connect-mom",
		title: "Connect with Mom",
		description: "Cultivating presence and social bonds.",
		status: "todo",
		isSynced: true,
	},
	{
		id: "task-time-mgt",
		goalId: "goal-mental-care",
		title: "Strategic Time Management",
		description: "Respecting work hours to prevent burnout.",
		status: "todo",
		isSynced: true,
	},
	{
		id: "task-english-prep",
		goalId: "goal-personal-hub",
		title: "Interview English Prep",
		description: "Practicing tech communication in English.",
		status: "todo",
		isSynced: true,
	},
	{
		id: "task-coding-tests",
		goalId: "goal-personal-hub",
		title: "Interview Coding Tests",
		description: "Solving algorithmic challenges and system design.",
		status: "todo",
		isSynced: true,
	},
	{
		id: "task-job-search",
		title: "International Job Search",
		description: "Researching remote-first opportunities in the EU/US.",
		status: "todo",
		isSynced: true,
	},
	{
		id: "task-linkedin",
		title: "Strategic Brand Update",
		description: "Refreshing LinkedIn and CV for international markets.",
		status: "todo",
		isSynced: true,
	},
	{
		id: "task-meditation",
		goalId: "goal-mental-care",
		title: "10-Min Mindfulness",
		description: "Centering the mind before strategic execution.",
		status: "todo",
		isSynced: true,
	},
	{
		id: "task-app-ui",
		goalId: "goal-personal-hub",
		title: "App UI Development",
		description: "Building the visual framework for the personal hub.",
		status: "todo",
		isSynced: true,
	},
	{
		id: "task-ui-home",
		parentTaskId: "task-app-ui",
		goalId: "goal-personal-hub",
		title: "Home Screen UI",
		description: "Implementing the main navigation landing page.",
		status: "todo",
		isSynced: true,
	},
	{
		id: "task-ui-tasks",
		parentTaskId: "task-app-ui",
		goalId: "goal-personal-hub",
		title: "Task Analytics View",
		description: "Developing the backlog visualization.",
		status: "todo",
		isSynced: true,
	},
	{
		id: "task-ui-goals",
		parentTaskId: "task-app-ui",
		goalId: "goal-personal-hub",
		title: "Goal Strategic View",
		description: "Visualizing high-level objectives.",
		status: "todo",
		isSynced: true,
	},
	{
		id: "task-ui-habits",
		parentTaskId: "task-app-ui",
		goalId: "goal-personal-hub",
		title: "Habit Streak View",
		description: "Visualizing behavioral performance.",
		status: "todo",
		isSynced: true,
	},
	{
		id: "task-ui-meanings",
		parentTaskId: "task-app-ui",
		goalId: "goal-personal-hub",
		title: "Meaning Dashboard View",
		description: "Visualizing the purpose-driven foundations.",
		status: "todo",
		isSynced: true,
	},
];
